#!/bin/bash

filename="$1"
ver="$2" 	
file=${filename%.*}
ext=${filename##*.}

if [ "$ext" = "py" ] || [ "$ext" = "PY" ]		
then
	if [ "$ver" = "-2" ]
	then
		#echo "python2"
		python $filename					# Python 2 
	else
		#echo "python3"
		python3 $filename					# Python 3
	fi

elif [ "$ext" = "cpp" ] || [ "$ext" = "CPP" ]
then
	#echo "c++"
	g++ $filename -o $file && ./$file 		# C++

elif [ "$ext" = "c" ] || [ "$ext" = "C" ]
then
	#echo "gcc"	
	gcc $filename -o $file && ./$file 		# C

elif [ "$ext" = "java" ]
then
	#echo "gcc"	
	javac $filename && java $file 			# Java

elif [ "$ext" = "flex" ]
then	
	#echo "flex"	
	flex $filename && gcc lex.yy.c && ./a.out 	#Flex

elif [ "$ext" = "sh" ]
then
	#echo "bash"	
	./$filename			#Bash

else
	echo "Unknown file type"
fi